name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

env:
  # two CPUs on runners
  MAKEFLAGS: j3
  # set some variables for Visual Studio
  MultiProcessorCompilation: true
  UseMultiToolTask: true
  EnforceProcessCountAcrossBuilds: true

jobs:
  build:
    name: build-windows-latest
    runs-on: windows-latest
    steps:
    - name: "Check out source"
      uses: actions/checkout@v2
    - name: Configure build for amd64
      uses: ilammy/msvc-dev-cmd@v1
      with:
          arch: amd64
    - name: "Build"
      run: ./msvc2019-build5.15.2-static.ps1
    - name: "List"
      run: ls
    - name: "Upload distribution artifact"
      if: runner.os == 'Windows' || runner.os == 'macOS'
      uses: actions/upload-artifact@v1
      with:
        name: openc2e-${{ github.sha }}-${{ runner.os }}.zip
        path: openc2e-${{ github.sha }}-${{ runner.os }}
